Models/PerfilUsuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Admisiones.Models
{
    public class PerfilUsuario
    {
        [Key]
        public int PerfilusuarioId { get; set; }

        [Display(Name = "Primer Nombre*")]
        public string PrimerNombre { get; set; }

        [Display(Name = "Segundo Nombre")]
        public string SegundoNombre { get; set; }

        [Display(Name = "Primer Apellido*")]
        public string PrimerApellido { get; set; }

        [Display(Name = "Segundo Apellido")]
        public string SegundoApellido { get; set; }

        [Display(Name = "Fecha de Nacimiento*")]
        [DataType(DataType.Date)]
        public DateTime FechaNacimiento { get; set; }

        [Display(Name = "Lugar de nacimiento*")]
        public string LugarNacimiento { get; set; }

        [Display(Name = "Genero*")]
        public string Genero { get; set; }

        [Display(Name = "Estado civil")]
        public string EstadoCivil { get; set; }

        [Display(Name = "Correo primario*")]
        [DataType(DataType.EmailAddress)]
        public string CorreoPrimario { get; set; }

        [Display(Name = "Correo secundario")]
        [DataType(DataType.EmailAddress)]
        public string CorreoSecundario { get; set; }

        [Display(Name = "Tipo de identificacion*")]
        public string TipoIdentificacion { get; set; }

        [Display(Name = "Numero de identificacion*")]
        public string NumeroIdentificacion { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string Celular { get; set; }

        [Display(Name = "Telefono primario*")]
        [DataType(DataType.PhoneNumber)]
        public string TelefonoPrimario { get; set; }

        [Display(Name = "Telefono secundario")]
        [DataType(DataType.PhoneNumber)]
        public string TelefonoSecundario { get; set; }

        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string Contrasena { get; set; }

        public List<Direccion> Direccions { get; set; }
    }
}

Controllers/PerfilUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admisiones.Models;
using Admisiones.Data;

namespace Admisiones.Controllers
{
    public class PerfilUsuariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PerfilUsuariosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PerfilUsuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.PerfilUsuarios.ToListAsync());
        }

        // GET: PerfilUsuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfilUsuario = await _context.PerfilUsuarios
                .FirstOrDefaultAsync(m => m.PerfilusuarioId == id);
            if (perfilUsuario == null)
            {
                return NotFound();
            }

            return View(perfilUsuario);
        }

        // GET: PerfilUsuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PerfilUsuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PerfilusuarioId,PrimerNombre,SegundoNombre,PrimerApellido,SegundoApellido,FechaNacimiento,LugarNacimiento,Genero,EstadoCivil,CorreoPrimario,CorreoSecundario,TipoIdentificacion,NumeroIdentificacion,Celular,TelefonoPrimario,TelefonoSecundario,Contrasena")] PerfilUsuario perfilUsuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(perfilUsuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(perfilUsuario);
        }

        // GET: PerfilUsuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfilUsuario = await _context.PerfilUsuarios.FindAsync(id);
            if (perfilUsuario == null)
            {
                return NotFound();
            }
            return View(perfilUsuario);
        }

        // POST: PerfilUsuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PerfilusuarioId,PrimerNombre,SegundoNombre,PrimerApellido,SegundoApellido,FechaNacimiento,LugarNacimiento,Genero,EstadoCivil,CorreoPrimario,CorreoSecundario,TipoIdentificacion,NumeroIdentificacion,Celular,TelefonoPrimario,TelefonoSecundario,Contrasena")] PerfilUsuario perfilUsuario)
        {
            if (id != perfilUsuario.PerfilusuarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(perfilUsuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerfilUsuarioExists(perfilUsuario.PerfilusuarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(perfilUsuario);
        }

        // GET: PerfilUsuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfilUsuario = await _context.PerfilUsuarios
                .FirstOrDefaultAsync(m => m.PerfilusuarioId == id);
            if (perfilUsuario == null)
            {
                return NotFound();
            }

            return View(perfilUsuario);
        }

        // POST: PerfilUsuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var perfilUsuario = await _context.PerfilUsuarios.FindAsync(id);
            _context.PerfilUsuarios.Remove(perfilUsuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerfilUsuarioExists(int id)
        {
            return _context.PerfilUsuarios.Any(e => e.PerfilusuarioId == id);
        }
    }
}

Controllers/RegistrousuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Admisiones.Data;
using Admisiones.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Admisiones.Controllers
{
    public class RegistrousuarioController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RegistrousuarioController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("/registroadmision")]
        public ActionResult PerfilUsuario()
        {

            var _provincia = _context.Provincia.ToList();

            ViewBag.Provincia = new SelectList(_provincia, "ProvinciaId", "Nombre");

            return View();
        }

        [HttpPost]
        [Route("/registroadmision")]
        public ActionResult PerfilUsuario(PerfilUsuarioVM perfilUsuarioVM)
        {
            bool cedula = _context.PerfilUsuarios.Where(nCed => nCed.NumeroIdentificacion.Equals(perfilUsuarioVM.PerfilUsuario.NumeroIdentificacion)).Any();

            if (!cedula)
            {
                PerfilUsuario prfUsr = new PerfilUsuario();
                prfUsr.PrimerNombre = perfilUsuarioVM.PerfilUsuario.PrimerNombre;
                prfUsr.SegundoNombre = perfilUsuarioVM.PerfilUsuario.SegundoNombre;
                prfUsr.PrimerApellido = perfilUsuarioVM.PerfilUsuario.PrimerApellido;
                prfUsr.SegundoApellido = perfilUsuarioVM.PerfilUsuario.SegundoApellido;
                prfUsr.FechaNacimiento = perfilUsuarioVM.PerfilUsuario.FechaNacimiento;
                prfUsr.LugarNacimiento = perfilUsuarioVM.PerfilUsuario.LugarNacimiento;
                prfUsr.Genero = perfilUsuarioVM.PerfilUsuario.Genero;
                prfUsr.EstadoCivil = perfilUsuarioVM.PerfilUsuario.EstadoCivil;
                prfUsr.CorreoPrimario = perfilUsuarioVM.PerfilUsuario.CorreoPrimario;
                prfUsr.CorreoSecundario = perfilUsuarioVM.PerfilUsuario.CorreoSecundario;
                prfUsr.TipoIdentificacion = perfilUsuarioVM.PerfilUsuario.TipoIdentificacion;
                prfUsr.NumeroIdentificacion = perfilUsuarioVM.PerfilUsuario.NumeroIdentificacion;
                prfUsr.Celular = perfilUsuarioVM.PerfilUsuario.Celular;
                prfUsr.TelefonoPrimario = perfilUsuarioVM.PerfilUsuario.TelefonoPrimario;
                prfUsr.TelefonoSecundario = perfilUsuarioVM.PerfilUsuario.TelefonoSecundario;
                prfUsr.Contrasena = perfilUsuarioVM.PerfilUsuario.Contrasena;
                _context.Add(prfUsr);
                _context.SaveChanges();

                Direccion dir = new Direccion();
                dir.PerfilusuarioId = prfUsr.PerfilusuarioId;
                dir.PaisOrigen = perfilUsuarioVM.Direccion.PaisOrigen;
                dir.Residencial = perfilUsuarioVM.Direccion.Residencial;
                dir.Descripcion = perfilUsuarioVM.Direccion.Descripcion;
                dir.Numero = perfilUsuarioVM.Direccion.Numero;
                _context.Add(dir);
                _context.SaveChanges();

                Provincia prv = new Provincia();
                prv.DireccionId = dir.DireccionId;
                prv.Nombre = perfilUsuarioVM.Provincia.Nombre;
                _context.Add(prv);
                _context.SaveChanges();

                Sector sctr = new Sector();
                sctr.ProvinciaId = prv.ProvinciaId;
                sctr.Nombre = perfilUsuarioVM.Sector.Nombre;
                _context.Add(sctr);
                _context.SaveChanges();

                System.Net.Mail.MailMessage msg = new System.Net.Mail.MailMessage();
                msg.To.Add(prfUsr.CorreoPrimario);
                msg.Subject = "Bienvenido al proceso de matriculacion UNAPEC";
                msg.SubjectEncoding = System.Text.Encoding.UTF8;
                msg.Body = "Bienvenido " + prfUsr.PrimerNombre + " " + prfUsr.SegundoNombre;
                msg.BodyEncoding = System.Text.Encoding.UTF8;
                msg.From = new System.Net.Mail.MailAddress(prfUsr.CorreoPrimario);

                System.Net.Mail.SmtpClient client = new System.Net.Mail.SmtpClient();
                client.Credentials = new System.Net.NetworkCredential("CORREO DE QUIEN LO ENVIA", "CONTRASENA");

                client.Port = 587;
                client.EnableSsl = true;

                client.Host = "smtp.gmail.com";

                try
                {
                    client.Send(msg);
                }
                catch (Exception)
                {

                    throw;
                }

                return View();
            }
            else
            {

                ViewBag.Nombre = "Existe";
                return View();

            }
        }

        public JsonResult Sectores(int provincia)
        {
            var _sectores = new SelectList(_context.Sector.Where(s => s.ProvinciaId.Equals(provincia)).ToList(), "SectorId", "Nombre");

            return Json(_sectores);
        }



        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

Views/Registrousuario/PerfilUsuario.cshtml
@model Admisiones.Models.PerfilUsuarioVM

@{
    ViewData["Title"] = "PerfilUsuario";
}

<h2>Registro de Postulante</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="PerfilUsuario" asp-controller="Registrousuario">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.PrimerNombre" class="control-label"></label>
                    <input id="PrimerNombre" asp-for="PerfilUsuario.PrimerNombre" placeholder="Tu primer apellido" class="form-control" required/>
                    <span asp-validation-for="PerfilUsuario.    " class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.SegundoNombre" class="control-label"></label>
                    <input asp-for="PerfilUsuario.SegundoNombre" placeholder="Tu segundo nombre" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.SegundoNombre" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.PrimerApellido" class="control-label"></label>
                    <input asp-for="PerfilUsuario.PrimerApellido" placeholder="Tu primer apellido" class="form-control" required/>
                    <span asp-validation-for="PerfilUsuario.PrimerApellido" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.SegundoApellido" class="control-label"></label>
                    <input asp-for="PerfilUsuario.SegundoApellido" placeholder="Tu segundo apellido" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.SegundoApellido" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.FechaNacimiento" class="control-label"></label>
                    <input asp-for="PerfilUsuario.FechaNacimiento" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.FechaNacimiento" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.LugarNacimiento" class="control-label"></label>
                    <input asp-for="PerfilUsuario.LugarNacimiento" placeholder="Tu lugar de nacimiento" class="form-control" required/>
                    <span asp-validation-for="PerfilUsuario.LugarNacimiento" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.Genero" class="control-label"></label>
                    @*<input asp-for="PerfilUsuario.Genero" class="form-control" />*@
                    <select class="form-control" asp-for="PerfilUsuario.Genero" required>
                        <option value="Femenino">Femenino</option>
                        <option value="Masculino">Masculino</option>
                    </select>
                    <span asp-validation-for="PerfilUsuario.Genero" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.EstadoCivil" class="control-label"></label>
                    @*<input asp-for="PerfilUsuario.EstadoCivil" class="form-control" />*@
                    <select class="form-control" asp-for="PerfilUsuario.EstadoCivil">
                        <option value="Soltero(a)">Soltero(a)</option>
                        <option value="Casado(a)">Casado(a)</option>
                        <option value="Divorciado(a)">Divorciado(a)</option>
                        <option value="Vuido(a)">Vuido(a)</option>
                        <option value="Separado(a)">Separado(a)</option>
                        <option value="Union Libre">Union Libre</option>
                        <option value="Otro">Otro</option>
                    </select>
                    <span asp-validation-for="PerfilUsuario.EstadoCivil" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.CorreoPrimario" class="control-label"></label>
                    <input asp-for="PerfilUsuario.CorreoPrimario" placeholder="correo@gmail.com" class="form-control" required/>
                    <span asp-validation-for="PerfilUsuario.CorreoPrimario" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.CorreoSecundario" class="control-label"></label>
                    <input asp-for="PerfilUsuario.CorreoSecundario" placeholder="correo@gmail.com" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.CorreoSecundario" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.TipoIdentificacion" class="control-label"></label>
                    @*<input asp-for="PerfilUsuario.TipoIdentificacion" class="form-control" />*@
                    <select class="form-control" asp-for="PerfilUsuario.TipoIdentificacion">
                        <option value="Cedula">Cedula</option>
                        <option value="Pasaporte">Pasaporte</option>
                        <option value="No. de Residencia (Extranjeros)">No. de Residencia (Extranjeros)</option>
                    </select>
                    <span asp-validation-for="PerfilUsuario.TipoIdentificacion" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.NumeroIdentificacion" class="control-label"></label>
                    <input asp-for="PerfilUsuario.NumeroIdentificacion" placeholder="000-0000000-0" class="form-control" required/>
                    <span asp-validation-for="PerfilUsuario.NumeroIdentificacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="Direccion.PaisOrigen" class="control-label"></label>
                    <select class="form-control" asp-for="Direccion.PaisOrigen">
                        <option value="Argentina">Argentina</option>
                        <option value="Bahamas">Bahamas</option>
                        <option value="Bolivia ">Bolivia</option>
                        <option value="Brasil">Brasil</option>
                        <option value="Canadá">Canadá</option>
                        <option value="Chile">Chile</option>
                        <option value="Colombia">Colombia</option>
                        <option value="Costa Rica">Costa Rica</option>
                        <option value="Cuba">Cuba</option>
                        <option value="Dominica">Dominica</option>
                        <option value="Ecuador">Ecuador</option>
                        <option value="El Salvador">El Salvador</option>
                        <option value="Estados Unidos">Estados Unidos</option>
                        <option value="Guatemala">Guatemala</option>
                        <option value="Haití">Haití</option>
                        <option value="Honduras">Honduras</option>
                        <option value="Jamaica">Jamaica</option>
                        <option value="México">México</option>
                        <option value="Nicaragua">Nicaragua</option>
                        <option value="Panamá">Panamá</option>
                        <option value="Paraguay">Paraguay</option>
                        <option value="Perú">Perú</option>
                        <option value="República Dominicana">República Dominicana</option>
                        <option value="Trinidad y Tobago">Trinidad y Tobago</option>
                        <option value="Uruguay">Uruguay</option>
                        <option value="Venezuela">Venezuela</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Provincia.Nombre" class="control-label"></label>
                    <select asp-for="Provincia.Nombre" asp-items="@ViewBag.Provincia" id="provincia" class="form-control"></select>
                    <span asp-validation-for="Provincia.Nombre" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="Sector.Nombre" class="control-label"></label>
                    <select asp-for="Sector.Nombre" id="Sector" class="form-control"></select>
                    <span asp-validation-for="Sector.Nombre" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Direccion.Residencial" class="control-label"></label>
                    <input asp-for="Direccion.Residencial" placeholder="Plaza las palmas" class="form-control" />
                    <span asp-validation-for="Direccion.Residencial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="Direccion.Descripcion" class="control-label"></label>
                    <input asp-for="Direccion.Descripcion" placeholder="Calle/Avenida" class="form-control" required/>
                    <span asp-validation-for="Direccion.Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Direccion.Numero" class="control-label"></label>
                    <input asp-for="Direccion.Numero" class="form-control" placeholder="Casa/Edificio" />
                    <span asp-validation-for="Direccion.Numero" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.Celular" class="control-label"></label>
                    <input asp-for="PerfilUsuario.Celular" class="form-control" placeholder="Ejemplo:8091234567" />
                    <span asp-validation-for="PerfilUsuario.Celular" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.TelefonoPrimario" class="control-label"></label>
                    <input asp-for="PerfilUsuario.TelefonoPrimario" placeholder="Ejemplo:8091234567" class="form-control" required/>
                    <span asp-validation-for="PerfilUsuario.TelefonoPrimario" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="PerfilUsuario.TelefonoSecundario" class="control-label"></label>
                    <input asp-for="PerfilUsuario.TelefonoSecundario" placeholder="Ejemplo:8091234567" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.TelefonoSecundario" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.Contrasena" class="control-label"></label>
                    <input id="Contra" asp-for="PerfilUsuario.Contrasena" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.Contrasena" class="text-danger"></span>
                </div>

                <div class="form-group col-md-6">
                    <label asp-for="PerfilUsuario.Contrasena" class="control-label">Confirmar Contrasena</label>
                    <input type="password" id="confirmacionContra" name="ConfirmacionContrasena" class="form-control" />
                    <span asp-validation-for="PerfilUsuario.Contrasena" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    $("#provincia").change(function () {
        $.ajax({
            url: "/Registrousuario/Sectores",
            type: "POST",
            dataType: "json",
            data: { provincia: $("#provincia").val() },
            success: function (resp) {
                console.log(resp);

                var respuesta = "";

                for (var i = 0; i < resp.length; i++) {
                    respuesta += "<option value='" + resp[i].value + ">" + resp[i].text + "</option>";
                }

                document.getElementById("Sector").innerHTML = respuesta;
            }
        });
    });

    if ($("#provincia").val() == null && $("#Sector").val() == null) {
        alert("Las contraseas no coinciden");
    }
</script>

<script src="~/js/ConfirmacionContrasena.js" asp-append-version="true"></script>